define HOST_UBOOT_TOOLS_RPI_INSTALL_BOOT_SCRIPT
	$(INSTALL) -m 0755 -D $(@D)/tools/boot.scr $(BINARIES_DIR)/rpi-firmware/boot.scr
endef
define HOST_UBOOT_TOOLS_RPI_INSTALL_ENVIMAGE
	$(INSTALL) -m 0755 -D $(@D)/tools/uboot-env.bin $(BINARIES_DIR)/rpi-firmware/uboot-env.bin
endef

ifneq ($(BR2_PACKAGE_HOST_UBOOT_TOOLS_BOOT_SCRIPT_SOURCE),)
HOST_UBOOT_TOOLS_POST_INSTALL_HOOKS+=HOST_UBOOT_TOOLS_RPI_INSTALL_BOOT_SCRIPT
endif
ifneq ($(BR2_PACKAGE_HOST_UBOOT_TOOLS_ENVIMAGE_SOURCE),)
HOST_UBOOT_TOOLS_POST_INSTALL_HOOKS+=HOST_UBOOT_TOOLS_RPI_INSTALL_ENVIMAGE
endif
